appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BPkpUutMOfx3epVEac1Q5VxSqzq9kL50CJABnnpEopLHiU9i+CEZPu5d9rQUk3x8XeOP+6T7B+Zct5u0Ct33Ivk3TTZxMPuDaDP0che0Rij3xSGEkl5txExmqcgR4rhZcZH3VzA3F21fL8IPMbq88Ti+Q5ERPxt4gl9pP7SQRwKxGqgHC5TkxsKv3I4HPGJBvnG7k3XB8wcY2/cc5vh4cJx6V8JJAkm1zoDAZ1TNFj8EUIpoDCVnaT0ENa8K/WLafMljYpuSjY4GvoXPKngQ7QvuqqZstFAH007e6XJubVQB9AGFjM+nXm7EkkI+mFGZKN2bj08RXTVRrZ628Iqz/Mu4cZ7Kxj783uk8NngQR9LvS9wl8lHiTJNQzR7Yaao89+6SqKz58SKNtvM/TTKl4Mkv9YfNACT644hD7Na/d8ojo3bYcsfwy3sKLANRBL6wRJheNAOfTcskPCNm6rTW3GS5+T5cS95YFQ+6UsxV2oD5s01HtZ+iUw1L0uSP+YtktvQG+nQ6qintUi7uSldFxzUPJEKG7lxTXEnVw3GpG4u4Vwcs2L95fB8gB+qGPyu6+wkGkaI39vgI9wKXNXsgCZiCdfst4d9rpwImGCT46qkAkt6rmO3aZsW5WWfNJyNS7u/NNTC2w0ey4ZYaYC8E0DtJSeZP9IYumMnWtfBFAWw=}
provider:
  win: azure
